"""Factory for building provider clients from settings."""

from __future__ import annotations

from apo_skillsmd.config import AppSettings
from apo_skillsmd.llm.anthropic import AnthropicLLMClient
from apo_skillsmd.llm.base import LLMClient, LLMResponse, LLMUsage, ToolCall
from apo_skillsmd.llm.cache import CachedLLMClient
from apo_skillsmd.llm.gemini import GeminiLLMClient
from apo_skillsmd.llm.minimax import MiniMaxLLMClient
from apo_skillsmd.llm.openai import OpenAICompatibleLLMClient
from apo_skillsmd.llm.qwen import QwenLLMClient
from apo_skillsmd.types import ProviderName


class MockLLMClient(LLMClient):
    """Deterministic test double used by smoke scripts and unit tests."""

    provider = ProviderName.MOCK

    def __init__(self, model: str = "mock-llm") -> None:
        self.model = model

    def complete(
        self,
        messages,
        *,
        tools=None,
        temperature: float = 0.2,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        system_prompt = messages[0].content if messages else ""
        tool_messages = [message for message in messages if message.role.value == "tool"]
        if "Skill name: Skill Mutator" in system_prompt:
            if not tool_messages:
                return LLMResponse(
                    message="Writing the mutated child skill package.",
                    tool_calls=[
                        ToolCall(
                            id="mock-mutation-1",
                            name="file_write",
                            args={
                                "path": "artifacts/child_skill/SKILL.md",
                                "content": (
                                    "---\n"
                                    "id: mock-mutated-skill\n"
                                    "name: Mock Mutated Skill\n"
                                    "description: Mutated child skill produced by the mock mutation agent.\n"
                                    "version: 0.1.0\n"
                                    "tags:\n"
                                    "  - mock\n"
                                    "  - mutation\n"
                                    "provenance:\n"
                                    "  source: mock_meta_skill\n"
                                    "  parents: []\n"
                                    "  generation: 0\n"
                                    "---\n\n"
                                    "# Mock Mutated Skill\n\n"
                                    "## Goal\n"
                                    "Handle the assigned task with a slightly improved workflow.\n\n"
                                    "## Workflow\n"
                                    "1. Inspect the task inputs.\n"
                                    "2. Create the required outputs.\n"
                                    "3. Return DONE.\n"
                                ),
                            },
                        ),
                        ToolCall(
                            id="mock-mutation-2",
                            name="file_write",
                            args={
                                "path": "artifacts/child_skill/scripts/main.py",
                                "content": (
                                    '"""Mock child skill generated by the mutation agent."""\n\n'
                                    "def main() -> str:\n"
                                    '    return "mutated"\n'
                                ),
                            },
                        ),
                    ],
                    usage=LLMUsage(input_tokens=12, output_tokens=10),
                )
            return LLMResponse(
                message="DONE: wrote artifacts/child_skill.",
                tool_calls=[],
                usage=LLMUsage(input_tokens=6, output_tokens=5),
                raw_response={"provider": "mock"},
            )
        if not tool_messages:
            return LLMResponse(
                message="Creating a deterministic mock output file.",
                tool_calls=[ToolCall(id="mock-call-1", name="bash", args={"cmd": "printf 'hello\\n' > out.txt"})],
                usage=LLMUsage(input_tokens=10, output_tokens=8),
            )
        return LLMResponse(
            message="DONE: mock execution finished.",
            tool_calls=[],
            usage=LLMUsage(input_tokens=6, output_tokens=4),
            raw_response={"provider": "mock"},
        )


def build_llm(settings: AppSettings) -> LLMClient:
    """Build the configured LLM backend and wrap it with cache when enabled."""

    provider = settings.llm.provider
    client: LLMClient

    if provider == ProviderName.MOCK:
        client = MockLLMClient(model=settings.llm.model)
    elif provider == ProviderName.MINIMAX:
        api_key = settings.api_key_for_provider(provider)
        if not api_key:
            raise ValueError("MINIMAX_API_KEY is required for the MiniMax provider.")
        base_url = settings.llm.base_url or "https://api.minimax.io/v1"
        client = MiniMaxLLMClient(
            model=settings.llm.model,
            api_key=api_key,
            base_url=base_url,
            timeout_sec=settings.llm.timeout_sec,
        )
    elif provider == ProviderName.OPENAI:
        api_key = settings.api_key_for_provider(provider)
        if not api_key:
            raise ValueError("OPENAI_API_KEY is required for the OpenAI provider.")
        if not settings.llm.base_url:
            raise ValueError("llm.base_url must be configured for the OpenAI provider.")
        client = OpenAICompatibleLLMClient(
            provider=ProviderName.OPENAI,
            model=settings.llm.model,
            api_key=api_key,
            base_url=settings.llm.base_url,
            timeout_sec=settings.llm.timeout_sec,
        )
    elif provider == ProviderName.ANTHROPIC:
        api_key = settings.api_key_for_provider(provider)
        if not api_key:
            raise ValueError("ANTHROPIC_API_KEY is required for the Anthropic provider.")
        client = AnthropicLLMClient(
            model=settings.llm.model,
            api_key=api_key,
            base_url=settings.llm.base_url,
        )
    elif provider == ProviderName.GEMINI:
        api_key = settings.api_key_for_provider(provider)
        if not api_key:
            raise ValueError("GEMINI_API_KEY is required for the Gemini provider.")
        client = GeminiLLMClient(model=settings.llm.model, api_key=api_key)
    elif provider == ProviderName.QWEN:
        api_key = settings.api_key_for_provider(provider)
        if not api_key:
            raise ValueError("QWEN_API_KEY is required for the Qwen provider.")
        client = QwenLLMClient(
            model=settings.llm.model,
            api_key=api_key,
            base_url=settings.llm.base_url,
        )
    else:  # pragma: no cover - protected by enum validation
        raise ValueError(f"Unsupported provider: {provider}")

    if settings.llm.use_cache:
        return CachedLLMClient(client, cache_dir=settings.llm.cache_dir)
    return client
